core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path('', home, name="home"),
]

socialnetwork/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('notifications.urls')),
    path('', include('core.urls')),
    path('', include('newsfeed.urls')),
    path('', include('friends.urls')),
    path('timeline/', include('userprofile.urls')),
    path('messages/', include('communications.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from .views import *

app_name = "profile"

urlpatterns = [
    path('edit-profile', ProfileEditView.as_view(), name="edit-profile"),
    path('users-info', Profileusersinfo.as_view(), name="users-info"),
    path('<slug:username>', TimelineView.as_view(), name="user-timeline"),
]

userprofile/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

from accounts.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING, related_name='profile')
    profile_image = models.ImageField(upload_to='avatars', default='avatars/guest.png')
    cover_image = models.ImageField(upload_to='avatars', default='avatars/cover.png')
    phone = models.CharField(max_length=20, blank=True)
    city = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=20, blank=True)

    def get_profile_image(self):
        if self.profile_image:
            return self.profile_image.url
        return settings.MEDIA_URL + self._meta.get_field('profile_image').get_default()

    def get_cover_image(self):
        if self.cover_image:
            return self.cover_image.url
        return settings.MEDIA_URL + self._meta.get_field('cover_image').get_default()


@receiver(post_save, sender=User)
def create_profile(sender, **kwargs):
    if kwargs.get('created', False):
        Profile.objects.create(user=kwargs['instance'])

userprofile/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, ListView

from accounts.models import User
from userprofile.models import Profile

import pandas as pd # For data processing
import numpy as np # For linear algebra
import matplotlib.pyplot as plt # For plotting


class TimelineView(DetailView):
    model = User
    template_name = "profile/user-profile.html"
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "user"
    object = None

    def get_object(self, queryset=None):
        return self.model.objects.select_related('profile').prefetch_related("posts").get(username=self.kwargs.get(self.slug_url_kwarg))

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class ProfileEditView(UpdateView):
    model = Profile
    template_name = "profile/edit-my-profile.html"
    context_object_name = "profile"
    object = None
    fields = "__all__"

    def get_object(self, queryset=None):
        return self.request.user.profile

    def post(self, request, *args, **kwargs):
        print(request.POST.get('first_name'))
        user = request.user
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.about = request.POST.get('about')
        if request.POST.get('gender') == "male":
            user.gender = "male"
        else:
            user.gender = "female"
        user.save()
        profile = user.profile
        profile.country = request.POST.get('country')
        profile.city = request.POST.get('city')
        profile.phone = request.POST.get('phone')
        profile.save()
        return redirect(reverse_lazy('profile:edit-profile'))

class Profileusersinfo(DetailView):
    model = Profile
    template_name = "profile/user-info.html"
    context_object_name = "profile"
    object = None
    fields = "__all__"

    def get_object(self):
        current_user_friends = pd.read_csv("row_data.csv")
        print("satvik")
        print(current_user_friends.head())
        data = pd.DataFrame(current_user_friends, columns=['ID','q11'])
        res=[]
        for i in data['q11']:
            res.append(i)
        fig, ax = plt.subplots(figsize=(12, 2), subplot_kw=dict(aspect="equal"), dpi= 80)
        labels2 = ['Male', 'Female']
        sizes2 = [res.count("male"), res.count("female")]
        plt.pie(sizes2, labels=labels2, autopct='%.0f%%')
        plt.savefig("gender-Python.png", bbox_inches='tight', dpi=300)

        return "gender-Python.png"

templates/profile/edit-my-profile.html
{% extends 'base.html' %}

{% block content %}

    <section>
        <div class="gap gray-bg">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row" id="page-contents">
                            <div class="col-lg-3">
                                <aside class="sidebar static">
                                    <div class="widget stick-widget">
                                        <h4 class="widget-title">Edit info</h4>
                                        <ul class="naves">
                                            <li>
                                                <i class="ti-info-alt"></i>
                                                <a href="{% url 'profile:edit-profile' %}" title="">Basic info</a>
                                            </li>
                                            <li>
                                                <i class="ti-heart"></i>
                                                <a href="{% url 'profile:users-info' %}" title="">User Infomation</a>
                                            </li>
                                        </ul>
                                    </div>
                                </aside>
                            </div>
                            <div class="col-lg-6">
                                <div class="central-meta">
                                    <div class="editing-info">
                                        <h5 class="f-title"><i class="ti-info-alt"></i> Edit Basic Information</h5>

                                        <form method="post" action="">
                                            {% csrf_token %}
                                            <div class="form-group half">
                                                <input type="text" id="input" name="first_name" required="required" value="{{ request.user.first_name }}"/>
                                                <label class="control-label" for="input">First Name</label><i class="mtrl-select"></i>
                                            </div>
                                            <div class="form-group half">
                                                <input type="text" name="last_name" required="required" value="{{ request.user.last_name }}"/>
                                                <label class="control-label" for="input">Last Name</label><i class="mtrl-select"></i>
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="phone" required="required" value="{{ profile.phone }}"/>
                                                <label class="control-label" for="input">Phone No.</label><i class="mtrl-select"></i>
                                            </div>
                                            <div class="form-radio">
                                                <div class="radio">
                                                    <label>
                                                        <input type="radio" {% if request.user.gender == "male" %} checked="checked" {% endif %} name="gender" value="male"><i class="check-box"></i>Male
                                                    </label>
                                                </div>
                                                <div class="radio">
                                                    <label>
                                                        <input type="radio" {% if request.user.gender == "female" %} checked="checked" {% endif %} name="gender" value="female"><i class="check-box"></i>Female
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="country" required="required" value="{{ profile.country }}"/>
                                                <label class="control-label" for="input">Country</label><i class="mtrl-select"></i>
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="city" required="required" value="{{ profile.city }}"/>
                                                <label class="control-label" for="input">City</label><i class="mtrl-select"></i>
                                            </div>
                                            <div class="form-group">
                                                <textarea rows="4" id="textarea" required="required" name="about">{{ request.user.about }}</textarea>
                                                <label class="control-label" for="textarea">About Me</label><i class="mtrl-select"></i>
                                            </div>
                                            <div class="submit-btns">
                                                <button type="button" class="mtr-btn"><span>Cancel</span></button>
                                                <button type="submit" class="mtr-btn"><span>Update</span></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <aside class="sidebar static">
                                </aside>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/profile/user-info.html
{% extends 'base.html' %}

{% block content %}

    <section>
        <div class="container">
            {% load static %}
            <h3>Graph</h3>
            <img src="{% static 'img/gender-Python.png' %}" alt="graph">
        </div>
    </section>

{% endblock %}