communications/urls.py
from django.urls import path
from .views import *

app_name = "communications"

urlpatterns = [
    path('', all_messages, name="all-messages"),
    path('<slug:friend>', messages_with_one_friend, name="messages-with-one-friend"),
]

core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path('', home, name="home"),
]

socialnetwork/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('notifications.urls')),
    path('', include('core.urls')),
    path('', include('newsfeed.urls')),
    path('', include('friends.urls')),
    path('timeline/', include('userprofile.urls')),
    path('messages/', include('communications.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

communications/models.py
import uuid  # Importing the uuid module for generating unique identifiers

from django.contrib.auth import get_user_model  # Importing the function to get the User model
from django.db import models  # Importing Django's models module

User = get_user_model()  # Getting the User model dynamically

# Creating a model for Chat Rooms
class Room(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # Unique identifier for the room
    author = models.ForeignKey(User, related_name='author_room', on_delete=models.CASCADE)  # Author of the room
    friend = models.ForeignKey(User, related_name='friend_room', on_delete=models.CASCADE)  # Friend in the room

# Creating a model for Messages within a Room
class Message(models.Model):
    author = models.ForeignKey(User, related_name='author_messages', on_delete=models.CASCADE)  # Message author
    friend = models.ForeignKey(User, related_name='friend_messages', on_delete=models.CASCADE)  # Message recipient
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.DO_NOTHING)  # Room associated with message
    message = models.TextField()  # Content of the message
    timestamp = models.DateTimeField(auto_now_add=True)  # Timestamp of when the message was created

    def __str__(self):
        return self.message + " " + str(self.timestamp)  # String representation of the message and its timestamp

communications/views.py
import json  # Importing JSON module for JSON handling

from django.contrib.auth.decorators import login_required  # Decorator for login requirement
from django.shortcuts import render, redirect  # Functions for rendering and redirection
from django.urls import reverse_lazy  # Utility for reversing URLs
from django.utils.safestring import mark_safe  # Utility for marking strings as safe

from accounts.models import User  # Importing the User model from accounts
from friends.models import Friend  # Importing the Friend model

# View to display all messages
@login_required(login_url=reverse_lazy("accounts:login"))  # Requires login; redirects to login if not logged in
def all_messages(request):
    friends = Friend.objects.friends(request.user)  # Fetching user's friends
    return render(request, "communications/all-messages.html", {'friends': friends})  # Rendering the messages template

# View for displaying conversation with a single friend
@login_required(login_url=reverse_lazy("accounts:login"))  # Requires login; redirects to login if not logged in
def messages_with_one_friend(request, friend):
    if request.user.username == friend:  # If user tries to view their own messages, redirect to all-messages
        return redirect(reverse_lazy('communications:all-messages'))

    try:
        if not User.objects.get(username=friend):  # If friend user doesn't exist, redirect to all-messages
            return redirect(reverse_lazy('communications:all-messages'))
    except:
        return redirect(reverse_lazy('communications:all-messages'))  # Redirect if any exception occurs

    friend_user = User.objects.get(username=friend)  # Getting the friend's user object

    # If the requested user and friend are not friends, redirect to all-messages
    if not Friend.objects.are_friends(request.user, friend_user):
        return redirect(reverse_lazy('communications:all-messages'))

    friends = Friend.objects.friends(request.user)  # Fetching user's friends
    return render(request, "communications/friend-messages.html", {
        'friends': friends,
        'friend_user': friend_user,
        'friend_name_json': mark_safe(json.dumps(friend)),  # Passing friend's name as JSON string
        'username': mark_safe(json.dumps(request.user.username)),  # Passing user's username as JSON string
    })

templates/communications/all-messages.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <main class="content">
        <div class="container p-0">

            <h1 class="h3 mb-3">Messages</h1>

            <div class="card">
                <div class="row g-0">
                    <div class="col-12 col-lg-5 col-xl-3 border-right">

                        <div class="px-4 d-none d-md-block">
                            <div class="d-flex align-items-center">
                                <div class="flex-grow-1">
                                    <input type="text" class="form-control my-3" placeholder="Search...">
                                </div>
                            </div>
                        </div>

                        {% for friend in friends %}
                            <a href="{% url 'communications:messages-with-one-friend' friend.username %}"
                               class="list-group-item list-group-item-action border-0">
                                <div class="d-flex align-items-start">
                                    <img src="https://bootdey.com/img/Content/avatar/avatar5.png"
                                         class="rounded-circle mr-1" alt="Vanessa Tucker" width="40" height="40">
                                    <div class="flex-grow-1 ml-3">
                                        {{ friend.get_full_name }}
                                        <div class="small"><span class="fas fa-circle chat-online"></span> Online</div>
                                    </div>
                                </div>
                            </a>
                        {% endfor %}

                        <hr class="d-block d-lg-none mt-1 mb-0">
                    </div>
                    <div class="col-12 col-lg-7 col-xl-9">
                        <div class="position-relative">
                            <div class="chat-messages p-4">
                                <h4 class="text-center">Select a user to chat with</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    {#    <section>#}
    {#        <div class="gap gray-bg">#}
    {#            <div class="container-fluid">#}
    {#                <div class="row">#}
    {#                    <div class="col-lg-12">#}
    {#                        <div class="row" id="page-contents">#}
    {#                            <div class="col-lg-3">#}
    {#                                <aside class="sidebar static">#}
    {#                                    <div class="widget stick-widget">#}
    {#                                        <h4 class="widget-title">Shortcuts</h4>#}
    {#                                        <ul class="naves">#}
    {#                                            <li>#}
    {#                                                <i class="ti-clipboard"></i>#}
    {#                                                <a href="{% url 'core:home' %}" title="">News feed</a>#}
    {#                                            </li>#}
    {#                                            <li>#}
    {#                                                <i class="ti-mouse-alt"></i>#}
    {#                                                <a href="#" title="">Inbox</a>#}
    {#                                            </li>#}
    {#                                            <li>#}
    {#                                                <i class="ti-user"></i>#}
    {#                                                <a href="#" title="">friends</a>#}
    {#                                            </li>#}
    {#                                        </ul>#}
    {#                                    </div><!-- Shortcuts -->#}
    {#                                </aside>#}
    {#                            </div><!-- sidebar -->#}
    {#                            <div class="col-lg-6">#}
    {#                                <div class="central-meta">#}
    {#                                    <div class="messages">#}
    {#                                        <h5 class="f-title"><i class="ti-bell"></i>All Messages </h5>#}
    {#                                        <div class="message-box row">#}
    {#                                            <ul class="peoples col-md-3">#}
    {#                                                {% for friend in friends %}#}
    {#                                                    <li>#}
    {#                                                        <figure>#}
    {#                                                            {% if friend.user.username == request.user.username %}#}
    {#                                                                {% if friend.friend.gender == 'male' %}#}
    {#                                                                    <img src="{% static 'images/male.jpg' %}" alt="male">#}
    {#                                                                {% else %}#}
    {#                                                                    <img src="{% static 'images/female.png' %}" alt="female">#}
    {#                                                                {% endif %}#}
    {#                                                            {% else %}#}
    {#                                                                {% if friend.user.gender == 'male' %}#}
    {#                                                                    <img src="{% static 'images/male.jpg' %}" alt="male">#}
    {#                                                                {% else %}#}
    {#                                                                    <img src="{% static 'images/female.png' %}" alt="female">#}
    {#                                                                {% endif %}#}
    {#                                                            {% endif %}#}
    {#<span class="status f-online"></span>#}
    {#                                                        </figure>#}
    {#                                                        <div class="people-name">#}
    {#                                                            {% if friend.user.username == request.user.username %}#}
    {#                                                                <a href="{% url 'communications:messages-with-one-friend' friend.friend.username %}">{{ friend.friend.username }}</a>#}
    {#                                                            {% else %}#}
    {#                                                                <a href="{% url 'communications:messages-with-one-friend' friend.user.username %}">{{ friend.user.username }}</a>#}
    {#                                                            {% endif %}#}
    {#                                                        </div>#}
    {#                                                    </li>#}
    {#                                                {% endfor %}#}
    {#                                            </ul>#}
    {#                                            <div class="peoples-mesg-box col-md-9">#}
    {#                                                <div class="text-center">#}
    {#                                                    Select message to start conversation#}
    {#                                                </div>#}
    {#                                                <div class="conversation-head">#}
    {#                                                    <figure><img src="images/resources/friend-avatar.jpg" alt=""></figure>#}
    {#                                                    <span>jason bourne <i>online</i></span>#}
    {#                                                </div>#}
    {#                                                <ul class="chatting-area">#}
    {#                                                    <li class="you">#}
    {#                                                        <figure><img src="images/resources/userlist-2.jpg" alt=""></figure>#}
    {#                                                        <p>what's liz short for? :)</p>#}
    {#                                                    </li>#}
    {#                                                    <li class="me">#}
    {#                                                        <figure><img src="images/resources/userlist-1.jpg" alt=""></figure>#}
    {#                                                        <p>Elizabeth lol</p>#}
    {#                                                    </li>#}
    {#                                                    <li class="me">#}
    {#                                                        <figure><img src="images/resources/userlist-1.jpg" alt=""></figure>#}
    {#                                                        <p>wanna know whats my second guess was?</p>#}
    {#                                                    </li>#}
    {#                                                    <li class="you">#}
    {#                                                        <figure><img src="images/resources/userlist-2.jpg" alt=""></figure>#}
    {#                                                        <p>yes</p>#}
    {#                                                    </li>#}
    {#                                                    <li class="me">#}
    {#                                                        <figure><img src="images/resources/userlist-1.jpg" alt=""></figure>#}
    {#                                                        <p>Disney's the lizard king</p>#}
    {#                                                    </li>#}
    {#                                                    <li class="me">#}
    {#                                                        <figure><img src="images/resources/userlist-1.jpg" alt=""></figure>#}
    {#                                                        <p>i know him 5 years ago</p>#}
    {#                                                    </li>#}
    {#                                                    <li class="you">#}
    {#                                                        <figure><img src="images/resources/userlist-2.jpg" alt=""></figure>#}
    {#                                                        <p>coooooooooool dude ;)</p>#}
    {#                                                    </li>#}
    {#                                                </ul>#}
    {#                                                <div class="message-text-container">#}
    {#                                                    <form method="post">#}
    {#                                                        <textarea></textarea>#}
    {#                                                        <button title="send"><i class="fa fa-paper-plane"></i></button>#}
    {#                                                    </form>#}
    {#                                                </div>#}
    {#                                            </div>#}
    {#                                        </div>#}
    {#                                    </div>#}
    {#                                </div>#}
    {#                            </div><!-- centerl meta -->#}
    {#                            <div class="col-lg-3">#}
    {#                            </div><!-- sidebar -->#}
    {#                        </div>#}
    {#                    </div>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#    </section>#}

{% endblock %}